/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRouteImport } from './routes/post'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/chat/$id': typeof ChatIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/chat/': typeof ChatIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/chat/$id': typeof ChatIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/chat': typeof ChatIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/wallet': typeof WalletRoute
  '/chat/$id': typeof ChatIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/chat/': typeof ChatIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/saved'
    | '/search'
    | '/wallet'
    | '/chat/$id'
    | '/jobs/$id'
    | '/product/$id'
    | '/seller/$id'
    | '/chat/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/saved'
    | '/search'
    | '/wallet'
    | '/chat/$id'
    | '/jobs/$id'
    | '/product/$id'
    | '/seller/$id'
    | '/chat'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/saved'
    | '/search'
    | '/wallet'
    | '/chat/$id'
    | '/jobs/$id'
    | '/product/$id'
    | '/seller/$id'
    | '/chat/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  WalletRoute: typeof WalletRoute
  ChatIdRoute: typeof ChatIdRoute
  JobsIdRoute: typeof JobsIdRoute
  ProductIdRoute: typeof ProductIdRoute
  SellerIdRoute: typeof SellerIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  WalletRoute: WalletRoute,
  ChatIdRoute: ChatIdRoute,
  JobsIdRoute: JobsIdRoute,
  ProductIdRoute: ProductIdRoute,
  SellerIdRoute: SellerIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
